name: ContiServer
description: HttpServer that logs to mongo
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  mongo_dart: "0.1.38"
  unittest: "0.10.0"
  http_server: ">=0.9.0 <0.10.0"
  http: ">=0.9.0 <0.10.0"
  route: ">=0.4.0 <0.5.0"
  logging: ">=0.9.0 <0.10.0"
